# Generated by Django 3.1 on 2020-10-05 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionTitle', models.CharField(max_length=255)),
                ('questionViews', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('aboutUser', models.URLField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.TextField(max_length=600)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='index.question')),
                ('verifiedUser', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='index.verified')),
            ],
        ),
    ]
