# Generated by Django 3.1 on 2020-10-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='verifiedUser',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='index.verified'),
        ),
        migrations.AlterField(
            model_name='verified',
            name='aboutUser',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
