# Generated by Django 3.1 on 2020-10-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201007_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentText',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionTitle',
            field=models.TextField(),
        ),
    ]
