# Generated by Django 3.1 on 2020-11-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20201024_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
